workflows:
  expo-build:
    name: Expo Build (Unsigned IPA)
    environment:
      vars:
        EXPO_CLI: latest    # Ensure you are using the latest Expo CLI
        NODE_VERSION: 16    # Specify the Node.js version
    scripts:
      # Install dependencies
      - name: Install dependencies
        script: |
          echo "Setting up Node.js..."
          nvm install $NODE_VERSION
          npm install

      # Build the Expo project for iOS
      - name: Build Expo project for iOS
        script: |
          npx expo install
          npx expo build:ios --no-wait --release-channel default --non-interactive
          
    artifacts:
      - ./dist/*.ipa
