workflows:
  ios-build:
    name: iOS Build (Unsigned IPA)
    environment:
      vars:
        NODE_VERSION: 16 # Specify the Node.js version
      xcode: latest       # Use the latest Xcode version
      cocoapods: default  # Use the default CocoaPods version
    scripts:
      # Install dependencies
      - name: Install dependencies
        script: |
          echo "Setting up Node.js..."
          nvm install $NODE_VERSION
          npm install
          cd ios && pod install

      # Build the IPA without signing
      - name: Build unsigned IPA
        script: |
          xcodebuild -workspace ios/MyApp.xcworkspace \
            -scheme MyApp \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/MyApp.xcarchive archive
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/MyApp.xcarchive \
            -exportPath $CM_BUILD_DIR/build/ \
            -exportOptionsPlist ios/ExportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/build/*.ipa
