workflows:
  ios-no-auth:
    name: iOS Build Without Expo Auth
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install --force
      
      - name: Install Expo CLI
        script: npm install -g @expo/cli --force
      
      - name: Generate iOS native project (skip login)
        script: |
          # Skip authentication by using --skip-dependency-update
          EXPO_NO_TELEMETRY=1 npx expo prebuild -p ios --clear --no-install
      
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install --repo-update
      
      - name: Create export options plist
        script: |
          cat > ios/ExportOptions.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF
      
      - name: Build iOS app with Xcode
        script: |
          cd ios
          
          # Get the scheme name (usually matches the project name)
          SCHEME_NAME=$(ls -1 *.xcworkspace | sed 's/\.xcworkspace$//')
          echo "Building scheme: $SCHEME_NAME"
          
          # Clean build directory
          rm -rf build/
          
          # Archive the app
          xcodebuild -workspace "$SCHEME_NAME.xcworkspace" \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath "build/$SCHEME_NAME.xcarchive" \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath "build/$SCHEME_NAME.xcarchive" \
            -exportPath build/ \
            -exportOptionsPlist ExportOptions.plist
          
          # List the generated files
          echo "Generated files:"
          find build/ -name "*.ipa" -type f
    
    artifacts:
      - ios/build/**/*.ipa
      - ios/build/**/*.app