workflows:
  ios-simple:
    name: Simple iOS Build
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install --force
      
      - name: Install Expo CLI
        script: npm install -g @expo/cli@latest --force
      
      - name: Check Expo CLI version
        script: npx expo --version
      
      - name: Clean and generate iOS project
        script: |
          # Remove existing native directories
          rm -rf ios android
          
          # Generate iOS native project
          npx expo prebuild --platform ios
      
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install
      
      - name: Build with Xcode (unsigned)
        script: |
          cd ios
          
          # Find the workspace file
          WORKSPACE=$(find . -name "*.xcworkspace" -maxdepth 1 | head -1)
          if [ -z "$WORKSPACE" ]; then
            echo "❌ No .xcworkspace found"
            exit 1
          fi
          
          # Get the scheme name
          SCHEME_NAME=$(basename "$WORKSPACE" .xcworkspace)
          echo "📱 Building scheme: $SCHEME_NAME"
          
          # Build for device (unsigned)
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath "build/$SCHEME_NAME.xcarchive" \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM=""
          
          # Create unsigned IPA
          mkdir -p build/unsigned
          cp -r "build/$SCHEME_NAME.xcarchive/Products/Applications/" "build/unsigned/"
          
          # Find the .app file and create IPA
          APP_FILE=$(find "build/unsigned" -name "*.app" | head -1)
          if [ -n "$APP_FILE" ]; then
            APP_NAME=$(basename "$APP_FILE")
            cd build/unsigned
            zip -r "${APP_NAME%.app}.ipa" "$APP_NAME"
            echo "✅ Created unsigned IPA: ${APP_NAME%.app}.ipa"
          fi
    
    artifacts:
      - ios/build/unsigned/*.ipa
      - ios/build/**/*.xcarchive