workflows:
  ios-free-apple:
    name: iOS Build with Free Apple ID
    environment:
      node: latest
      expo: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Generate iOS native project
        script: npx expo prebuild -p ios
      - name: Build iOS app for devices
        script: npx eas build --platform ios --profile production --non-interactive --local
    artifacts:
      - dist/**/*.ipa
